# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cg}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tomohiro, TAIRA"]
  s.date = %q{2010-06-04}
  s.default_executable = %q{cg}
  s.description = %q{cg is A Ruby based contents generator}
  s.email = %q{tomohiro.t+github@gmail.com}
  s.executables = ["cg"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.html",
     "README.mkd"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.mkd",
     "Rakefile",
     "VERSION",
     "bin/cg",
     "cg.gemspec",
     "lib/cg/convert.rb",
     "lib/cg/rebuild.rb",
     "lib/cg/scratch.rb",
     "lib/cg/server.rb",
     "lib/contents_generator.rb",
     "skel/.exclude",
     "skel/images/please_puts_image_here",
     "skel/markdown/.htaccess",
     "skel/markdown/index.mkd",
     "skel/scripts/create-elements.js",
     "skel/scripts/disqus.js",
     "skel/styles/cg.css",
     "skel/styles/default.css",
     "skel/styles/fonts-min.css",
     "skel/styles/iphone.css",
     "skel/styles/reset-min.css",
     "skel/templates/.htaccess",
     "skel/templates/disqus.erb",
     "skel/templates/html.erb",
     "spec/cg_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://rubygems.org/gems/cg}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{HTML Contents Generator}
  s.test_files = [
    "spec/cg_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<tilt>, [">= 0.9"])
      s.add_runtime_dependency(%q<erubis>, [">= 2.6.5"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 1.6.3.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rack>, [">= 1.1.0"])
      s.add_dependency(%q<tilt>, [">= 0.9"])
      s.add_dependency(%q<erubis>, [">= 2.6.5"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_dependency(%q<rdiscount>, [">= 1.6.3.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rack>, [">= 1.1.0"])
    s.add_dependency(%q<tilt>, [">= 0.9"])
    s.add_dependency(%q<erubis>, [">= 2.6.5"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    s.add_dependency(%q<rdiscount>, [">= 1.6.3.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

